'name: binder
dependencies:
  - python=3.10
  - conda-forge::numpy=1.22
  - conda-forge::scipy=1.8
  - defaults::pandas=1.4
  - defaults::matplotlib=3.5
  - conda-forge::ffmpeg=5.0
  - conda-forge::dask=2022.2
  - conda-forge::fastparquet=0.8
  - conda-forge::pyarrow=7.0
  - conda-forge::jupyter=1.0
  - conda-forge::ipywidgets=7.6
  - conda-forge::pydub=0.25
  - conda-forge::scikit-learn=1.0
  - conda-forge::jupyter_contrib_nbextensions=0.5
  - pip=22.0
  - pip:
    - ipython==8.0
    - jupyterlab_latex==3.1
    - nbgitpuller
