#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False
jupyter labextension install @jupyterlab/latex
jupyter serverextension enable --py nbgitpuller --sys-prefix

wget -q -O beethoven_mp3.zip "https://mediatech.aalto.fi/images/research/virtualacoustics/recordings/beethoven_mp3.zip"
wget -q -O mozart_mp3.zip "https://mediatech.aalto.fi/images/research/virtualacoustics/recordings/mozart_mp3.zip"
wget -q -O bruckner_mp3.zip "https://mediatech.aalto.fi/images/research/virtualacoustics/recordings/bruckner_mp3.zip"
wget -q -O mahler_mp3.zip "https://mediatech.aalto.fi/images/research/virtualacoustics/recordings/mahler_mp3.zip"
wget -q -O full.zip "https://sound.media.mit.edu/resources/KEMAR/full.zip"

mkdir anechoic
mkdir hrtf

unzip -o beethoven_mp3.zip -d anechoic/beethoven
unzip -o mozart_mp3.zip -d anechoic/mozart
unzip -o bruckner_mp3.zip -d anechioc/bruckner
unzip -o mahler_mp3.zip -d anechioc/mahler
unzip -o full.zip -d hrtf

rm -rf beethoven_mp3.zip
rm -rf mozart_mp3.zip
rm -rf bruckner_mp3.zip
rm -rf mahler_mp3.zip
rm -rf full.zip

mkdir train
mkdir test
mkdir validate
mkdir train_recipe
mkdir test_recipe
mkdir validate_recipe

wget -q -O full.zip "https://reflections.speakeasy.services/full.zip"

unzip -o full.zip .

rm -rf code.zip

unzip -o -j train.zip -d train
unzip -o -j test.zip -d test
unzip -o -j validate.zip -d validate

rm -rf train.zip
rm -rf test.zip
rm -rf validate.zip

unzip -o -j train/train_recipe.zip -d train_recipe
unzip -o -j test/test_recipe.zip -d test_recipe
unzip -o -j validate/validate_recipe.zip -d validate_recipe

rm -rf train/train_recipe.zip
rm -rf test/test_recipe.zip
rm -rf validate/validate_recipe.zip
